apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-service-a-to-service-b
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: service-a
  policyTypes:
  - Egress
  egress:
  - to:  # Allow external internet access
    - ipBlock:
        cidr: 0.0.0.0/0

